name: Deploy to Lambda
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release --verbose
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: cp target/release/sampleapi bootstrap
      - run: zip lambda.zip bootstrap
      - run: aws lambda update-function-code --function-name=LukeDavis --zip-file=fileb://lambda.zip